### ISSUE TITLE
Tildele medlemsnummer

### ISSUE THREAD

**Issue by kimkochrasmussen** [mogensen/fdfapp#19]
Hvad gør vi med nye børn, som jo typisk først får et medlemsnummer efter noget tid.
Kunne man forestille sig at man oprettede dem, og at man så efterfølgende kan påsætte medlemsnummer på dem...???

**Comment by mogensen** [comment]
Medlemsnummeret kan nu tilføjes på medlemmer som ikke allerede har et.
Medlemsnumre kan ikke ændres.

**Comment by mogensen** [comment]
Implemented in #459117e

**Comment by kimkochrasmussen** [comment]
Virker ikke. Kan ikke tilføje på Asger
