### ISSUE TITLE
Upload pic på deltagere

### ISSUE THREAD

**Issue by kimkochrasmussen** [mogensen/fdfapp#7]

**Comment by kimkochrasmussen** [comment]
Optimering på billede-upload: Billeder skal automatisk resizeses og evt croppes - ved intet om det, men tænker der må ligge færdige biblioteker der gør netop det...?

**Comment by mogensen** [comment]
Billeder bliver automatisk skalleret til 300x300 px
Se actions/participants_images.go:Create() og actions/participants_images.go:Update()
